"""
Export dbt Docs Artifacts from Databricks/ADLS to Local Airflow.

Downloads dbt documentation artifacts (``index.html``, ``manifest.json``,
``catalog.json``) generated by the ``dbt docs generate`` Databricks
notebook to the local Airflow filesystem at
``/opt/airflow/data/dbt-docs/``.

Two download methods are attempted (in order):
1. **Azure Blob Storage (gold container)** — uses ``azure-storage-blob``
   SDK with the storage account name and key from environment variables.
2. **Local fallback** — checks if files have been pre-staged at the
   target directory (e.g., via a bind mount or manual copy).

If neither method succeeds, the operator logs a warning and exits
gracefully — the dbt docs remain available on Databricks DBFS at
``/dbfs/mnt/w3c-data/dbt-docs/``.
"""

from __future__ import annotations

import json
import logging
import os

logger = logging.getLogger(__name__)

LOCAL_DOCS_DIR = "/opt/airflow/data/dbt-docs"
REQUIRED_FILES = ["index.html", "manifest.json", "catalog.json"]

# ADLS gold container where dbt_docs notebook writes artifacts
GOLD_CONTAINER = "gold"
BLOB_PREFIX = "dbt-docs"


def export_dbt_docs_to_airflow(**context) -> None:
    """Download dbt docs from Azure Blob Storage (gold container) to local Airflow.

    Falls back gracefully if credentials or the SDK are unavailable.
    """
    os.makedirs(LOCAL_DOCS_DIR, exist_ok=True)

    # ── Method 1: Azure Blob Storage SDK ──────────────────────────────
    # Check Databricks-convention names (AZURE_STORAGE_ACCOUNT / AZURE_STORAGE_KEY)
    # and fall back to legacy Airflow names (STORAGE_ACCOUNT_NAME / STORAGE_ACCESS_KEY).
    storage_account = os.environ.get("AZURE_STORAGE_ACCOUNT") or os.environ.get("STORAGE_ACCOUNT_NAME", "")
    storage_key = os.environ.get("AZURE_STORAGE_KEY") or os.environ.get("STORAGE_ACCESS_KEY", "")

    if storage_account and storage_key:
        try:
            _download_with_azure_sdk(storage_account, storage_key)
            if _verify_docs():
                return
        except Exception as exc:
            logger.warning(f"Azure Blob SDK download failed: {exc}")
    else:
        logger.info(
            "AZURE_STORAGE_ACCOUNT / AZURE_STORAGE_KEY (or "
            "STORAGE_ACCOUNT_NAME / STORAGE_ACCESS_KEY) not configured "
            "(only needed for dbt docs sync; not required for core pipeline)"
        )

    # ── Method 2: Check if pre-staged locally ─────────────────────────
    if _verify_docs():
        logger.info(f"dbt docs artifacts already present at {LOCAL_DOCS_DIR}")
        return

    logger.warning(
        f"dbt docs artifacts not downloaded to {LOCAL_DOCS_DIR}. "
        f"They remain available on Databricks DBFS at "
        f"/dbfs/mnt/w3c-data/dbt-docs/. "
        f"To enable automatic sync, set AZURE_STORAGE_ACCOUNT and "
        f"AZURE_STORAGE_KEY (or STORAGE_ACCOUNT_NAME and "
        f"STORAGE_ACCESS_KEY) environment variables and ensure "
        f"azure-storage-blob is installed."
    )


def _download_with_azure_sdk(account_name: str, account_key: str) -> None:
    """Download dbt docs from Azure Blob Storage gold container."""
    try:
        from azure.storage.blob import BlobServiceClient
    except ImportError:
        logger.warning("azure-storage-blob SDK not installed. Install it with: pip install azure-storage-blob")
        return

    conn_str = (
        f"DefaultEndpointsProtocol=https;"
        f"AccountName={account_name};"
        f"AccountKey={account_key};"
        f"EndpointSuffix=core.windows.net"
    )

    blob_service = BlobServiceClient.from_connection_string(conn_str)
    container_client = blob_service.get_container_client(GOLD_CONTAINER)

    # Check if container exists
    try:
        container_client.get_container_properties()
    except Exception:
        logger.warning(f"Container '{GOLD_CONTAINER}' not found or not accessible in storage account '{account_name}'")
        return

    downloaded = 0
    for filename in REQUIRED_FILES:
        blob_path = f"{BLOB_PREFIX}/{filename}"
        local_path = os.path.join(LOCAL_DOCS_DIR, filename)

        try:
            blob_client = container_client.get_blob_client(blob_path)
            with open(local_path, "wb") as f:
                f.write(blob_client.download_blob().readall())
            logger.info(f"Downloaded {blob_path} -> {local_path}")
            downloaded += 1
        except Exception as exc:
            logger.warning(f"Could not download {blob_path}: {exc}")

    if downloaded == 0:
        logger.warning(
            f"No dbt docs artifacts found in container '{GOLD_CONTAINER}'. "
            f"Ensure the dbt_docs Databricks notebook ran and copied "
            f"artifacts to the gold container."
        )
    else:
        logger.info(f"Downloaded {downloaded}/{len(REQUIRED_FILES)} dbt docs artifacts")


def _verify_docs() -> bool:
    """Check if all required dbt docs artifacts exist locally.

    Returns ``True`` if all three files (``index.html``, ``manifest.json``,
    ``catalog.json``) are present and ``catalog.json`` contains valid JSON.
    """
    all_present = True
    for filename in REQUIRED_FILES:
        path = os.path.join(LOCAL_DOCS_DIR, filename)
        exists = os.path.isfile(path)
        if not exists:
            logger.debug(f"Missing dbt docs artifact: {filename}")
            all_present = False

    # Validate catalog.json is valid JSON
    catalog_path = os.path.join(LOCAL_DOCS_DIR, "catalog.json")
    if os.path.isfile(catalog_path):
        try:
            with open(catalog_path) as f:
                json.load(f)
            logger.info("catalog.json is valid JSON")
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning(f"catalog.json is invalid: {exc}")
            all_present = False

    return all_present
