name: Reusable Terraform

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        dir: [terraform/part_a, terraform/part_b]
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"
      - name: Terraform fmt
        run: cd ${{ matrix.dir }} && terraform fmt --check
      - name: Terraform init
        run: cd ${{ matrix.dir }} && terraform init -backend=false
      - name: Terraform validate
        run: cd ${{ matrix.dir }} && terraform validate
      - name: Terraform test
        run: cd ${{ matrix.dir }} && terraform test
